"""add_billing_interval_to_subscriptions

Revision ID: 162747512bab
Revises: dbb4c6635ae6
Create Date: 2026-08-28 09:53:02.273808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162747512bab'
down_revision: Union[str, None] = 'dbb4c6635ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('billing_interval', sa.String(length=20), nullable=False, server_default='month'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'billing_interval')
    # ### end Alembic commands ###
