"""create_subscriptions_table

Revision ID: dbb4c6635ae6
Revises: 0001_initial
Create Date: 2026-08-27 15:24:28.870113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb4c6635ae6'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_org_id'), 'subscriptions', ['org_id'], unique=True)
    op.drop_index('ix_cps_client_id', table_name='client_pipeline_states')
    op.drop_index('ix_cps_org_id', table_name='client_pipeline_states')
    op.create_index(op.f('ix_client_pipeline_states_client_id'), 'client_pipeline_states', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_pipeline_states_org_id'), 'client_pipeline_states', ['org_id'], unique=False)
    op.drop_index('ix_clients_source_ref', table_name='clients')
    op.drop_constraint('industries_slug_key', 'industries', type_='unique')
    op.drop_index('ix_industries_slug', table_name='industries')
    op.create_index(op.f('ix_industries_slug'), 'industries', ['slug'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_industries_slug'), table_name='industries')
    op.create_index('ix_industries_slug', 'industries', ['slug'], unique=False)
    op.create_unique_constraint('industries_slug_key', 'industries', ['slug'])
    op.create_index('ix_clients_source_ref', 'clients', ['source_ref'], unique=False)
    op.drop_index(op.f('ix_client_pipeline_states_org_id'), table_name='client_pipeline_states')
    op.drop_index(op.f('ix_client_pipeline_states_client_id'), table_name='client_pipeline_states')
    op.create_index('ix_cps_org_id', 'client_pipeline_states', ['org_id'], unique=False)
    op.create_index('ix_cps_client_id', 'client_pipeline_states', ['client_id'], unique=False)
    op.drop_index(op.f('ix_subscriptions_org_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
